### ISSUE TITLE
Local devices permissions not granted on older versions if android

### ISSUE THREAD

**Issue by juanjgit** [Mobile-Artificial-Intelligence/maid#263]
Hi

I am trying to setup Maid as an Ollama Client. I select "ollama" as "API Type" and the remote URL as "http://192.168.1.53:11434". I tested the URL in a browser and I get the generic OK mesage form my ollama server. But when I click on the "Remote Model" list, it is empty.

Please, see attached screenshot:

![photo_2024-01-10_23-26-54](https://github.com/Mobile-Artificial-Intelligence/maid/assets/3613326/89aeb557-f0f1-4efd-8bd9-855665e5a177)

I sniffed the network and Maid is not querying the ollama server when entering the URL or when clicking the topdown list.

OS: Android 11
RAM: 5Gb
Maid: 1.1.7

**Comment by danemadsen** [comment]
ill look into it. Out of curiosity are you using a VPN though? I noticed that causes some issues sometimes

**Comment by danemadsen** [comment]
I cant reproduce your error though from my experimenting its possible you haven't granted the permission to access nearby devices.

The nearby devices permission is required to access devices on your network, if you do not grant it you will not be able to use Ollama.

**Comment by juanjgit** [comment]
You seem to be right. The log show the message "Nearby Devices - Permission denied", but I was not asked to grant these permissions on installation and I do not see how to grant them once installed.

**Comment by WildBanjos** [comment]
Hello. It appears this has _not_ been resolved in the latest release 1.1.8 in Android. Tested on fresh install, same issue as previously noted.

When adding local ollama server no models show in dropdown and no popup requesting nearby devices permission appeared. 
![Screenshots_2024-01-22-05-03-15](https://github.com/Mobile-Artificial-Intelligence/maid/assets/117058715/31234ed3-b320-48c3-b63e-5baa46dbea0f)

Log shows the permission is preventing connection. 
![Screenshot_20240122-050025](https://github.com/Mobile-Artificial-Intelligence/maid/assets/117058715/ed3d705d-79df-420c-911c-992c68a6ea06)

Checking the list of allowed permissions in android settings, nearby devices is not listed as an option for thr app.

**Comment by juanjgit** [comment]
I know the drop-down list is not working because you are using libraries that are not compatible with Android 11. But Android 11 is still not in end of life and it has about 20% of the market share. As far as I know this permission that only works in Android 12+ is only used to auto-discover the models offered by the ollama server. All other features of this app work in Android 11. Could you add an option to enter the model name manually if the OS does not support this autodiscover (Android < 12)

**Comment by danemadsen** [comment]
> I know the drop-down list is not working because you are using libraries that are not compatible with Android 11. But Android 11 is still not in end of life and it has about 20% of the market share. As far as I know this permission that only works in Android 12+ is only used to auto-discover the models offered by the ollama server. All other features of this app work in Android 11. Could you add an option to enter the model name manually if the OS does not support this autodiscover (Android < 12)

yeah i can do that. Not sure whats going on with the perms though because it apparently doesn't work on android 12 either

**Comment by WildBanjos** [comment]
One suggestion I have is to maybe add a small "test connection" or " reload model list" button and tie the api request to the button rather than the remote url box. When looking at that log, it seems like the app is attempting to make the connection continuously as the url/ip is being typed rather than waiting for the finished string. Perhaps that is confusing the permission request or it may have trouble issuing the permission request while a textbox is in context/focus. 

I made a (very rough) mockup of the reload button. 

![mockup (20240131024135)](https://github.com/Mobile-Artificial-Intelligence/maid/assets/117058715/4f94fdce-3dfb-41f0-afaa-a88b8941d5de)

**Comment by danemadsen** [comment]
> One suggestion I have is to maybe add a small "test connection" or " reload model list" button and tie the api request to the button rather than the remote url box. When looking at that log, it seems like the app is attempting to make the connection continuously as the url/ip is being typed rather than waiting for the finished string. Perhaps that is confusing the permission request or it may have trouble issuing the permission request while a textbox is in context/focus.
> 
> I made a (very rough) mockup of the reload button just to show positioning.
> 
> ![mockup (20240131024135)](https://private-user-images.githubusercontent.com/117058715/301095884-4f94fdce-3dfb-41f0-afaa-a88b8941d5de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDI0MzQsIm5iZiI6MTcwNjc0MjEzNCwicGF0aCI6Ii8xMTcwNTg3MTUvMzAxMDk1ODg0LTRmOTRmZGNlLTNkZmItNDFmMC1hZmFhLWE4OGI4OTQxZDVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQyMzAyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmI3NDEwMmExOTVkMDNkYjk5NzAzMTZkOGM5NDZmNDgxYjlkYmQ2M2ExYWRjN2JmZjU2NWRlNTBkMGZlNzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.irHqmqRyf5k3_T0H-3bmNXm5somXcxPAhzKjtbR7zXQ)

Good idea

**Comment by laaledesiempre** [comment]
hi people, just to make a little of explanation here if someone comes looking for this issue:

If your ollama server is receiving an api/chat as 404 means that doesnt have the model you are asking for. 

> but i cant select the model on the options.

they are working on solving this, they say that is bc of android libraries, i'm not sure about that bc i'm currently on the las version of lineage os and it doesnt work. 

> Then there is a solution or workaround?

yes, you can pull the default (llama2) model, it should wor.k

> but i'm hosting the ollama server on a mobile device/similar, it cant handle such a big model.

same here, saddly then you can't use it yet. developers are making a lot of effort on solving all the problems so. be nice with them! 

if you find some other workaround to change the model, leave it here! you can see logs on settings if you wanna share it!.

**Comment by laaledesiempre** [comment]
suggest to, as someone said, leaving you to put the model name. and show the error message if it does not find the model. also changing the issue name as it seems that permision is not the reason of the error but the input.

**Comment by laaledesiempre** [comment]
This keep failing on last release. 
### IMPORTANT

on the logs there is no call to list the models, 
https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models

this should do this:
- when you write the remote url THEN call to `api/tags`
- use that response to get names and adding it to the list showed by the "Remote Model" dropdown
- then, when you select a model, it should set it on the future api calls to `api/chat`

**Comment by danemadsen** [comment]
Ok i updated the permissions functions hopefully it may work now idk

**Comment by WildBanjos** [comment]
Starting from release 1.2.2, this appears to be fixed. When adding a local ollama server, it pops up with a permissions request. Granting it allows connection to the ollama server and the model drop down is correctly populated. Functionality from there is to be expected, and chatting can begin.

**Comment by danemadsen** [comment]
> Starting from release 1.2.2, this appears to be fixed. When adding a local ollama server, it pops up with a permissions request. Granting it allows connection to the ollama server and the model drop down is correctly populated. Functionality from there is to be expected, and chatting can begin. 

Sounds good to me
