### ISSUE TITLE
Version 1.3.0 starts with an error message and black window

### ISSUE THREAD

**Issue by Meincrakker** [Mobile-Artificial-Intelligence/maid#609]
Hi, the terminal output is:

```
./maid.AppImage 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libbabylon.so': libonnxruntime.so.1.18.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      Babylon.lib (package:babylon_tts/src/babylon.dart:24)
#3      Babylon.init (package:babylon_tts/src/babylon.dart:48)
<asynchronous suspension>
#4      main (package:maid/main.dart:16)
<asynchronous suspension>

```

and the window is just blank:
![image](https://github.com/user-attachments/assets/709f5309-903a-46bd-8d5a-bc527d4d04ec)

Edit:
Problem is in the newest version 1.3.0, the 1.2.9 version runs fine

**Comment by danemadsen** [comment]
Its related to text to speech which is why its only in 1.3.0

**Comment by danemadsen** [comment]
@Meincrakker does the zip release work?

**Comment by Meincrakker** [comment]
No, the zip release is also broken. It starts with the same Black screen and this error message:
```
./maid 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libbabylon.so': libonnxruntime.so.1.18.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      Babylon.lib (package:babylon_tts/src/babylon.dart:24)
#3      Babylon.init (package:babylon_tts/src/babylon.dart:48)
<asynchronous suspension>
#4      main (package:maid/main.dart:16)
<asynchronous suspension>
```

**Comment by danemadsen** [comment]
fixed https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/10537373610

**Comment by nate2014jatc** [comment]
The current 1.3.0 AppImage file on the release page still presents this issue
